In [29]:
# Add the Pandas dependency
import pandas as pd
import numpy as np
import os
import calendar
import datetime

# Files to load
#equities_data_to_load = os.path.join("Resources/Equities.csv")
#covid_data_to_load = os.path.join("Resources/national-history.csv")
logistic_analysis_data_to_load = os.path.join("Resources/logistic_regression_data.csv")

In [30]:
# Read the equities data file and store it in a Pandas DataFrame
#equities_data_df = pd.read_csv(equities_data_to_load)

#Covid_data_df = pd.read_csv(covid_data_to_load)

logistic_analysis_df = pd.read_csv(logistic_analysis_data_to_load)

In [31]:
logistic_analysis_df.head()

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1

In [32]:
logistic_analysis_df.dtypes

symbol                                           object
date                                             object
volume                                            int64
volume_previousday                                int64
volume_greater_previousday                        int64
volume_deathIncrease_up                           int64
volume_hospitalizedIncrease_up                    int64
volume_negativeIncrease_up                        int64
volume_positiveIncrease_up                        int64
volume_totalTestResultsIncrease_up                int64
high                                            float64
high_previousday                                float64
high_greater_previousday                          int64
high_deathIncrease_up                             int64
high_hospitalizedIncrease_up                      int64
high_negativeIncrease_up                          int64
high_positiveIncrease_up                          int64
high_totalTestResultsIncrease_up                  int64
iexClose                                        float64
iexClose_previousday                            float64
iexClose_greater_previousday                      int64
iexClose_deathIncrease_up                         int64
iexClose_hospitalizedIncrease_up                  int64
iexClose_negativeIncrease_up                      int64
iexClose_positiveIncrease_up                      int64
iexClose_totalTestResultsIncrease_up              int64
deathIncrease                                     int64
deathIncrease_previousday                         int64
deathIncrease_greater_previousday                 int64
hospitalizedIncrease                              int64
hospitalizedIncrease_previousday                  int64
hospitalizedIncrease_greater_previousday          int64
negativeIncrease                                  int64
negativeIncrease_previousday                      int64
negativeIncrease_greater_previousday              int64
positiveIncrease                                  int64
positiveIncrease_previousday                      int64
positiveIncrease_greater_previousday              int64
totalTestResultsIncrease                          int64
totalTestResultsIncrease_previousday              int64
totalTestResultsIncrease_greater_previousday      int64
dtype: object

In [33]:
logistic_analysis_df

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623463,ZVO,12/23/2020,195564,132125,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623464,ZYME,12/23/2020,217828,227603,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623465,ZYNE,12/23/2020,1062396,1019326,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623466,ZYXI,12/23/2020,402081,352613,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623467,TRUE,12/23/2020,403929,1643700,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1

In [34]:
# Converting to best datatype primarily to remove the decimals off of the comparison columns
logistic_analysis_df = logistic_analysis_df.convert_dtypes()

In [35]:
logistic_analysis_df.dtypes

symbol                                           string
date                                             string
volume                                            Int64
volume_previousday                                Int64
volume_greater_previousday                        Int64
volume_deathIncrease_up                           Int64
volume_hospitalizedIncrease_up                    Int64
volume_negativeIncrease_up                        Int64
volume_positiveIncrease_up                        Int64
volume_totalTestResultsIncrease_up                Int64
high                                            float64
high_previousday                                float64
high_greater_previousday                          Int64
high_deathIncrease_up                             Int64
high_hospitalizedIncrease_up                      Int64
high_negativeIncrease_up                          Int64
high_positiveIncrease_up                          Int64
high_totalTestResultsIncrease_up                  Int64
iexClose                                        float64
iexClose_previousday                            float64
iexClose_greater_previousday                      Int64
iexClose_deathIncrease_up                         Int64
iexClose_hospitalizedIncrease_up                  Int64
iexClose_negativeIncrease_up                      Int64
iexClose_positiveIncrease_up                      Int64
iexClose_totalTestResultsIncrease_up              Int64
deathIncrease                                     Int64
deathIncrease_previousday                         Int64
deathIncrease_greater_previousday                 Int64
hospitalizedIncrease                              Int64
hospitalizedIncrease_previousday                  Int64
hospitalizedIncrease_greater_previousday          Int64
negativeIncrease                                  Int64
negativeIncrease_previousday                      Int64
negativeIncrease_greater_previousday              Int64
positiveIncrease                                  Int64
positiveIncrease_previousday                      Int64
positiveIncrease_greater_previousday              Int64
totalTestResultsIncrease                          Int64
totalTestResultsIncrease_previousday              Int64
totalTestResultsIncrease_greater_previousday      Int64
dtype: object

In [36]:
logistic_analysis_df

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623463,ZVO,12/23/2020,195564,132125,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623464,ZYME,12/23/2020,217828,227603,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623465,ZYNE,12/23/2020,1062396,1019326,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623466,ZYXI,12/23/2020,402081,352613,1,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623467,TRUE,12/23/2020,403929,1643700,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1

In [41]:
# Replacing 0's in volume_deathIncrease_up column if both values are higher on current day vs previous day
logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'volume_deathIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'volume_deathIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'volume_deathIncrease_up'], value = 1)

In [43]:
# Replacing 0's in volume volume_hospitalizedIncrease_up column with 1's if the volume and hospitilizations are higher on current day than previous day
logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'volume_hospitalizedIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'volume_hospitalizedIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'volume_hospitalizedIncrease_up'], value = 1)

In [65]:
# Replacing 0's in volume volume_negativeIncrease_up column with 1's if the volume and negativeIncrease are higher on current day than previous day


logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'volume_negativeIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'volume_negativeIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'volume_negativeIncrease_up'], value = 1)

In [44]:
# Replacing 0's in volume volume_positiveIncrease_up column with 1's if the volume and positiveIncrease are higher on current day than previous day


logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'volume_positiveIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'volume_positiveIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'volume_positiveIncrease_up'], value = 1)

In [45]:
# Replacing 0's in volume volume_totalTestResultsIncrease_up column with 1's if the volume and totalTestResultsIncrease are higher on current day than previous day


logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'volume_totalTestResultsIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'volume_totalTestResultsIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['volume_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'volume_totalTestResultsIncrease_up'], value = 1)

In [46]:
logistic_analysis_df

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623463,ZVO,12/23/2020,195564,132125,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623464,ZYME,12/23/2020,217828,227603,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623465,ZYNE,12/23/2020,1062396,1019326,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623466,ZYXI,12/23/2020,402081,352613,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623467,TRUE,12/23/2020,403929,1643700,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1

In [51]:
# Replacing 0's in iexClose_deathIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'iexClose_deathIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'iexClose_deathIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'iexClose_deathIncrease_up'], value = 1)

In [52]:
# Replacing 0's in iexClose_hospitalizedIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'iexClose_hospitalizedIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'iexClose_hospitalizedIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'iexClose_hospitalizedIncrease_up'], value = 1)

In [53]:
# Replacing 0's in iexClose_negativeIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'iexClose_negativeIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'iexClose_negativeIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'iexClose_negativeIncrease_up'], value = 1)

In [54]:
# Replacing 0's in iexClose_positiveIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'iexClose_positiveIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'iexClose_positiveIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'iexClose_positiveIncrease_up'], value = 1)

In [55]:
# Replacing 0's in iexClose_totalTestResultsIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'iexClose_totalTestResultsIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'iexClose_totalTestResultsIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['iexClose_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'iexClose_totalTestResultsIncrease_up'], value = 1)

In [56]:
logistic_analysis_df

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623463,ZVO,12/23/2020,195564,132125,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623464,ZYME,12/23/2020,217828,227603,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623465,ZYNE,12/23/2020,1062396,1019326,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623466,ZYXI,12/23/2020,402081,352613,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623467,TRUE,12/23/2020,403929,1643700,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1

In [57]:
# Replacing 0's in high_deathIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'high_deathIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'high_deathIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['deathIncrease_greater_previousday'] == 1),
                       'high_deathIncrease_up'], value = 1)

In [58]:
# Replacing 0's in high_hospitalizedIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'high_hospitalizedIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'high_hospitalizedIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['hospitalizedIncrease_greater_previousday'] == 1),
                       'high_hospitalizedIncrease_up'], value = 1)

In [59]:
# Replacing 0's in high_negativeIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'high_negativeIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'high_negativeIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['negativeIncrease_greater_previousday'] == 1),
                       'high_negativeIncrease_up'], value = 1)

In [60]:
# Replacing 0's in high_positiveIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'high_positiveIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'high_positiveIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['positiveIncrease_greater_previousday'] == 1),
                       'high_positiveIncrease_up'], value = 1)

In [61]:
# Replacing 0's in high_totalTestResultsIncrease_up column if both values are higher on current day vs previous day


logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'high_totalTestResultsIncrease_up'] = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'high_totalTestResultsIncrease_up'].replace(to_replace = logistic_analysis_df.loc[(logistic_analysis_df['high_greater_previousday'] == 1) & 
                       (logistic_analysis_df['totalTestResultsIncrease_greater_previousday'] == 1),
                       'high_totalTestResultsIncrease_up'], value = 1)

In [62]:
logistic_analysis_df

,symbol,date,volume,volume_previousday,volume_greater_previousday,volume_deathIncrease_up,volume_hospitalizedIncrease_up,volume_negativeIncrease_up,volume_positiveIncrease_up,volume_totalTestResultsIncrease_up,...,hospitalizedIncrease_greater_previousday,negativeIncrease,negativeIncrease_previousday,negativeIncrease_greater_previousday,positiveIncrease,positiveIncrease_previousday,positiveIncrease_greater_previousday,totalTestResultsIncrease,totalTestResultsIncrease_previousday,totalTestResultsIncrease_greater_previousday
0,A,8/20/2020,318382,1651518,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
1,AA,8/20/2020,1543881,5460701,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
2,AAAU,8/20/2020,151621,584100,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
3,AACG,8/20/2020,10963,36708,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
4,AADR,8/20/2020,177,1191,0,0,0,0,0,0,...,0,208472,243232,0,43844,45073,0,864210,832115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623463,ZVO,12/23/2020,195564,132125,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623464,ZYME,12/23/2020,217828,227603,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623465,ZYNE,12/23/2020,1062396,1019326,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623466,ZYXI,12/23/2020,402081,352613,1,1,1,0,1,1,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1
623467,TRUE,12/23/2020,403929,1643700,0,0,0,0,0,0,...,1,304962,268046,1,224526,193008,1,1791481,1770133,1

In [68]:
# Create the output file (CSV).
output_data_file = "logistic_regression_test.csv"

In [69]:
# Export the City_Data into a CSV.
logistic_analysis_df.to_csv(output_data_file, index_label="data_index")